[package]
name = "rtd-transaction-builder"
version = "0.1.0"
authors = ["Stefan Stanciulescu <stefan@linkulabs.com>", "Brandon Williams <brandon@linkulabs.com>"]
license = "Apache-2.0"
edition = "2024"
description = "Transaction API for the Rust SDK for the Rtd Blockchain"

[dependencies]
base64ct = { version = "1.8", features = ["std"] }
bcs = "0.1.6"
serde = { version = "1.0", features = ["derive"] }
serde_with = { version = "3.15", default-features = false, features = ["alloc"] }
rtd-types = { package = "rtd-sdk-types", version = "0.1.0", path = "../rtd-sdk-types", features = ["serde", "hash"] }
thiserror = "2.0"
serde_json = { version = "1.0.145" }

# [dev-dependencies]
# anyhow = "1.0"
# rand = "0.8"
# serde_json = "1.0"
# rtd-crypto = { package = "rtd-crypto", path = "../rtd-crypto" , features = ["ed25519"] }
# rtd-graphql-client = { package = "rtd-graphql-client", path = "../rtd-graphql-client" }
# rtd-types = { package = "rtd-sdk-types", path = "../rtd-sdk-types", features = ["rand"] }
# tokio = { version = "1.0", features = ["full"] }
